twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/components': components
        '%kernel.project_dir%/templates/guidelines': guidelines

when@test:
    twig:
        strict_variables: true
